---
- hosts: all
  vars:
    supervisord_conf_dir: /etc/supervisor/conf.d
    supervisord_eventlistener_name: supervisord-eventlistener-test
    supervisord_eventlistener_command: echo "Hello World"
    supervisord_eventlistener_events: PROCESS_STATE_EXITED,PROCESS_STATE_FATAL
  tasks:
    - name: check if eventlistener name is configured correctly in supervisord-eventlistener-test.conf
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: '[eventlistener:{{supervisord_eventlistener_name}}]'
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if command is configured correctly in supervisord-eventlistener-test.conf
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: command={{supervisord_eventlistener_command}}
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if events are configured correctly in supervisord-eventlistener-test.conf
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: events={{supervisord_eventlistener_events}}
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if stopasgroup is configured correctly in supervisord-eventlistener-test.conf
      vars:
        supervisord_stopasgroup: False
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: stopasgroup=false
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if user is configured correctly in supervisord-eventlistener-test.conf
      vars:
        supervisord_eventlistener_username: nobody
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: user={{supervisord_eventlistener_username}}
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if environment is configured correctly in supervisord-eventlistener-test.conf
      vars:
        supervisord_eventlistener_env:
          FOO: BAR
          BING: BAZ
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: environment=BING="BAZ",FOO="BAR"
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if stopwaitsecs is configured correctly in supervisord-eventlistener-test.conf
      vars:
        supervisord_eventlistener_addl_settings:
          stopwaitsecs: 30
          startretries: 6
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: stopwaitsecs=30
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if startretries is configured correctly in supervisord-eventlistener-test.conf
      vars:
        supervisord_eventlistener_addl_settings:
          stopwaitsecs: 30
          startretries: 6
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: startretries=6
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if stdout_logfile is configured correctly in supervisord-eventlistener-test.conf
      vars:
        supervisord_eventlistener_stdout_logfile: /tmp/supervisord-eventlistener-test-5-stdout.log
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: stdout_logfile={{supervisord_eventlistener_stdout_logfile}}
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if stdout_logfile_maxbytes is configured correctly in supervisord-eventlistener-test.conf
      vars:
        supervisord_eventlistener_stdout_logfile_maxbytes: 0
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: stdout_logfile_maxbytes=0
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)

    - name: check if redirect_stderr is configured correctly in supervisord-eventlistener-test.conf
      vars:
        supervisord_eventlistener_redirect_stderr: True
        supervisord_eventlistener_stderr_logfile: /tmp/supervisord-eventlistener-test-stderr.log
      block:
        - include_role:
            name: '{{playbook_dir}}'
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: redirect_stderr=true
            state: present
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)
        - lineinfile:
            path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
            line: stderr_logfile={{supervisord_eventlistener_stderr_logfile}}
            state: absent
          check_mode: yes
          register: result
          failed_when: (result | changed) or (result | failed)
