---
- hosts: all
  vars:
    supervisord_eventlistener_name: supervisord-eventlistener-test
    supervisord_eventlistener_command: echo test
    supervisord_eventlistener_events: RUNNING,STOPPED
    supervisord_stopasgroup: False
    supervisord_eventlistener_user: nobody
    supervisord_eventlistener_env:
      FOO: BAR
      BING: BAZ
    supervisord_eventlistener_addl_settings:
      stopwaitsecs: 30
      startretries: 6
    supervisord_eventlistener_stdout_logfile: /tmp/supervisord-eventlistener-test-stdout.log
    supervisord_eventlistener_stdout_logfile_maxbytes: 0
    supervisord_eventlistener_redirect_stderr: True
  roles:
    - role: '{{playbook_dir}}'
  tasks:

    - name: check if command is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: command={{supervisord_eventlistener_command}}
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if events are configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: events={{supervisord_eventlistener_events}}
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if stopasgroup is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: stopasgroup=false
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if user is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: user={{supervisord_eventlistener_user}}
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if environment is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: environment=FOO="BAR",BING="BAZ"
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if stopwaitsecs is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: stopwaitsecs=30
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if startretries is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: startretries=6
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if stdout_logfile is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: stdout_logfile={{supervisord_eventlistener_stdout_logfile}}
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if stdout_logfile_maxbytes is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: stdout_logfile_maxbytes=0
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

    - name: check if redirect_stderr is configured correctly in supervisord-eventlistener-test.conf
      lineinfile:
        path: '{{supervisord_conf_dir}}/{{supervisord_eventlistener_name}}.conf'
        line: redirect_stderr=true
        state: present
      check_mode: yes
      register: result
      failed_when: (result | changed) or (result | failed)

